import React from "react";
import { Audio, Sequence, staticFile, useVideoConfig } from "remotion";
import manifest from "./voiceover/manifest.json";

/**
 * Promo narration layer. Each line in src/voiceover/manifest.json is dropped
 * onto the timeline at its `atSec` mark, reading public/voiceover/vo-<id>.mp3
 * (generated by scripts/generate-voiceover.js).
 *
 * Remotion bundles staticFile() assets at render time, so any clip that has
 * not been generated yet would fail the render. To keep partial runs safe,
 * the set of available ids is injected at build time via the
 * REMOTION_VO_IDS env var (comma-separated). When unset, all manifest clips
 * are assumed present.
 */
const availableIds: number[] | null = (() => {
  const raw =
    typeof process !== "undefined" ? process.env.REMOTION_VO_IDS : undefined;
  if (!raw) return null; // null = "all present"
  return raw
    .split(",")
    .map((s) => parseInt(s.trim(), 10))
    .filter((n) => !Number.isNaN(n));
})();

export const Voiceover: React.FC<{ volume?: number }> = ({ volume = 1 }) => {
  const { fps } = useVideoConfig();
  const clips = manifest.clips.filter(
    (c) => availableIds === null || availableIds.includes(c.id)
  );
  return (
    <>
      {clips.map((c) => (
        <Sequence key={c.id} from={Math.round(c.atSec * fps)} name={`VO ${c.id}`}>
          <Audio src={staticFile(`voiceover/vo-${c.id}.mp3`)} volume={volume} />
        </Sequence>
      ))}
    </>
  );
};
